// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: protobuf.proto

package api_merchant

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
}

func (x *AuthorRequest) Reset() {
	*x = AuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorRequest) ProtoMessage() {}

func (x *AuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorRequest.ProtoReflect.Descriptor instead.
func (*AuthorRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthorRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthorRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExisted  int64 `protobuf:"varint,1,opt,name=IsExisted,json=isExisted,proto3" json:"IsExisted,omitempty"`
	User_Id    int64 `protobuf:"varint,2,opt,name=User_Id,json=userId,proto3" json:"User_Id,omitempty"`
	Authorized int64 `protobuf:"varint,3,opt,name=Authorized,json=authorized,proto3" json:"Authorized,omitempty"`
}

func (x *AuthorRespone) Reset() {
	*x = AuthorRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorRespone) ProtoMessage() {}

func (x *AuthorRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorRespone.ProtoReflect.Descriptor instead.
func (*AuthorRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorRespone) GetIsExisted() int64 {
	if x != nil {
		return x.IsExisted
	}
	return 0
}

func (x *AuthorRespone) GetUser_Id() int64 {
	if x != nil {
		return x.User_Id
	}
	return 0
}

func (x *AuthorRespone) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

type SearchBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId        int64  `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
	BillStatus    int64  `protobuf:"varint,2,opt,name=BillStatus,json=billStatus,proto3" json:"BillStatus,omitempty"`
	ItemId        int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount        int64  `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	CustomerId    int64  `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerPhone string `protobuf:"bytes,6,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
	BillDesc      string `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
	ItemName      string `protobuf:"bytes,8,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	CustomerName  string `protobuf:"bytes,9,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
}

func (x *SearchBillRequest) Reset() {
	*x = SearchBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBillRequest) ProtoMessage() {}

func (x *SearchBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBillRequest.ProtoReflect.Descriptor instead.
func (*SearchBillRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *SearchBillRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *SearchBillRequest) GetBillStatus() int64 {
	if x != nil {
		return x.BillStatus
	}
	return 0
}

func (x *SearchBillRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SearchBillRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SearchBillRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SearchBillRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *SearchBillRequest) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

func (x *SearchBillRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SearchBillRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type SearchBillRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId        int64  `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
	BillStatus    int64  `protobuf:"varint,2,opt,name=BillStatus,json=billStatus,proto3" json:"BillStatus,omitempty"`
	ItemId        int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount        int64  `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	CustomerId    int64  `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerPhone string `protobuf:"bytes,6,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
	BillDesc      string `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
	ItemName      string `protobuf:"bytes,8,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	CustomerName  string `protobuf:"bytes,9,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
}

func (x *SearchBillRespone) Reset() {
	*x = SearchBillRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBillRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBillRespone) ProtoMessage() {}

func (x *SearchBillRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBillRespone.ProtoReflect.Descriptor instead.
func (*SearchBillRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *SearchBillRespone) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *SearchBillRespone) GetBillStatus() int64 {
	if x != nil {
		return x.BillStatus
	}
	return 0
}

func (x *SearchBillRespone) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SearchBillRespone) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SearchBillRespone) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SearchBillRespone) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *SearchBillRespone) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

func (x *SearchBillRespone) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SearchBillRespone) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId     int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount     int64  `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	CustomerId int64  `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	BillDesc   string `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBillRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateBillRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateBillRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateBillRequest) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

type CreateBillRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSaved int64 `protobuf:"varint,1,opt,name=IsSaved,json=isSaved,proto3" json:"IsSaved,omitempty"`
}

func (x *CreateBillRespone) Reset() {
	*x = CreateBillRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRespone) ProtoMessage() {}

func (x *CreateBillRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRespone.ProtoReflect.Descriptor instead.
func (*CreateBillRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBillRespone) GetIsSaved() int64 {
	if x != nil {
		return x.IsSaved
	}
	return 0
}

var File_protobuf_proto protoreflect.FileDescriptor

var file_protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0d,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x66, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x73, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x22, 0x9d, 0x02,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9d, 0x02,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7f, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x22, 0x2d,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x32, 0xc9, 0x02,
	0x0a, 0x19, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4d, 0x69, 0x64, 0x64, 0x6c, 0x65,
	0x77, 0x61, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0a, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x22, 0x0a, 0x2f, 0x76, 0x31,
	0x2f, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x68, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72,
	0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22,
	0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x30,
	0x01, 0x12, 0x66, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12,
	0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protobuf_proto_rawDescOnce sync.Once
	file_protobuf_proto_rawDescData = file_protobuf_proto_rawDesc
)

func file_protobuf_proto_rawDescGZIP() []byte {
	file_protobuf_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_rawDescData)
	})
	return file_protobuf_proto_rawDescData
}

var file_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protobuf_proto_goTypes = []interface{}{
	(*AuthorRequest)(nil),     // 0: api.merchant.AuthorRequest
	(*AuthorRespone)(nil),     // 1: api.merchant.AuthorRespone
	(*SearchBillRequest)(nil), // 2: api.merchant.SearchBillRequest
	(*SearchBillRespone)(nil), // 3: api.merchant.SearchBillRespone
	(*CreateBillRequest)(nil), // 4: api.merchant.CreateBillRequest
	(*CreateBillRespone)(nil), // 5: api.merchant.CreateBillRespone
}
var file_protobuf_proto_depIdxs = []int32{
	0, // 0: api.merchant.MerchantMiddlewareService.UserAuthor:input_type -> api.merchant.AuthorRequest
	2, // 1: api.merchant.MerchantMiddlewareService.SearchBill:input_type -> api.merchant.SearchBillRequest
	4, // 2: api.merchant.MerchantMiddlewareService.CreateBill:input_type -> api.merchant.CreateBillRequest
	1, // 3: api.merchant.MerchantMiddlewareService.UserAuthor:output_type -> api.merchant.AuthorRespone
	3, // 4: api.merchant.MerchantMiddlewareService.SearchBill:output_type -> api.merchant.SearchBillRespone
	5, // 5: api.merchant.MerchantMiddlewareService.CreateBill:output_type -> api.merchant.CreateBillRespone
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_proto_init() }
func file_protobuf_proto_init() {
	if File_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBillRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_depIdxs,
		MessageInfos:      file_protobuf_proto_msgTypes,
	}.Build()
	File_protobuf_proto = out.File
	file_protobuf_proto_rawDesc = nil
	file_protobuf_proto_goTypes = nil
	file_protobuf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MerchantMiddlewareServiceClient is the client API for MerchantMiddlewareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantMiddlewareServiceClient interface {
	UserAuthor(ctx context.Context, in *AuthorRequest, opts ...grpc.CallOption) (*AuthorRespone, error)
	SearchBill(ctx context.Context, in *SearchBillRequest, opts ...grpc.CallOption) (MerchantMiddlewareService_SearchBillClient, error)
	CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillRespone, error)
}

type merchantMiddlewareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantMiddlewareServiceClient(cc grpc.ClientConnInterface) MerchantMiddlewareServiceClient {
	return &merchantMiddlewareServiceClient{cc}
}

func (c *merchantMiddlewareServiceClient) UserAuthor(ctx context.Context, in *AuthorRequest, opts ...grpc.CallOption) (*AuthorRespone, error) {
	out := new(AuthorRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/UserAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) SearchBill(ctx context.Context, in *SearchBillRequest, opts ...grpc.CallOption) (MerchantMiddlewareService_SearchBillClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MerchantMiddlewareService_serviceDesc.Streams[0], "/api.merchant.MerchantMiddlewareService/SearchBill", opts...)
	if err != nil {
		return nil, err
	}
	x := &merchantMiddlewareServiceSearchBillClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MerchantMiddlewareService_SearchBillClient interface {
	Recv() (*SearchBillRespone, error)
	grpc.ClientStream
}

type merchantMiddlewareServiceSearchBillClient struct {
	grpc.ClientStream
}

func (x *merchantMiddlewareServiceSearchBillClient) Recv() (*SearchBillRespone, error) {
	m := new(SearchBillRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *merchantMiddlewareServiceClient) CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillRespone, error) {
	out := new(CreateBillRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/CreateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantMiddlewareServiceServer is the server API for MerchantMiddlewareService service.
type MerchantMiddlewareServiceServer interface {
	UserAuthor(context.Context, *AuthorRequest) (*AuthorRespone, error)
	SearchBill(*SearchBillRequest, MerchantMiddlewareService_SearchBillServer) error
	CreateBill(context.Context, *CreateBillRequest) (*CreateBillRespone, error)
}

// UnimplementedMerchantMiddlewareServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantMiddlewareServiceServer struct {
}

func (*UnimplementedMerchantMiddlewareServiceServer) UserAuthor(context.Context, *AuthorRequest) (*AuthorRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAuthor not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) SearchBill(*SearchBillRequest, MerchantMiddlewareService_SearchBillServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchBill not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) CreateBill(context.Context, *CreateBillRequest) (*CreateBillRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}

func RegisterMerchantMiddlewareServiceServer(s *grpc.Server, srv MerchantMiddlewareServiceServer) {
	s.RegisterService(&_MerchantMiddlewareService_serviceDesc, srv)
}

func _MerchantMiddlewareService_UserAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).UserAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/UserAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).UserAuthor(ctx, req.(*AuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_SearchBill_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchBillRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MerchantMiddlewareServiceServer).SearchBill(m, &merchantMiddlewareServiceSearchBillServer{stream})
}

type MerchantMiddlewareService_SearchBillServer interface {
	Send(*SearchBillRespone) error
	grpc.ServerStream
}

type merchantMiddlewareServiceSearchBillServer struct {
	grpc.ServerStream
}

func (x *merchantMiddlewareServiceSearchBillServer) Send(m *SearchBillRespone) error {
	return x.ServerStream.SendMsg(m)
}

func _MerchantMiddlewareService_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/CreateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).CreateBill(ctx, req.(*CreateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantMiddlewareService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.merchant.MerchantMiddlewareService",
	HandlerType: (*MerchantMiddlewareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAuthor",
			Handler:    _MerchantMiddlewareService_UserAuthor_Handler,
		},
		{
			MethodName: "CreateBill",
			Handler:    _MerchantMiddlewareService_CreateBill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchBill",
			Handler:       _MerchantMiddlewareService_SearchBill_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf.proto",
}
