// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: protobuf.proto

package api_merchant

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=Username,json=username,proto3" json:"Username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,json=password,proto3" json:"Password,omitempty"`
}

func (x *AuthorRequest) Reset() {
	*x = AuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorRequest) ProtoMessage() {}

func (x *AuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorRequest.ProtoReflect.Descriptor instead.
func (*AuthorRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthorRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthorRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExisted  int64  `protobuf:"varint,1,opt,name=IsExisted,json=isExisted,proto3" json:"IsExisted,omitempty"`
	User_Id    string `protobuf:"bytes,2,opt,name=User_Id,json=userId,proto3" json:"User_Id,omitempty"`
	Authorized int64  `protobuf:"varint,3,opt,name=Authorized,json=authorized,proto3" json:"Authorized,omitempty"`
}

func (x *AuthorRespone) Reset() {
	*x = AuthorRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorRespone) ProtoMessage() {}

func (x *AuthorRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorRespone.ProtoReflect.Descriptor instead.
func (*AuthorRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorRespone) GetIsExisted() int64 {
	if x != nil {
		return x.IsExisted
	}
	return 0
}

func (x *AuthorRespone) GetUser_Id() string {
	if x != nil {
		return x.User_Id
	}
	return ""
}

func (x *AuthorRespone) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

type SearchBillRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId        int64       `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
	BillStatus    int64       `protobuf:"varint,2,opt,name=BillStatus,json=billStatus,proto3" json:"BillStatus,omitempty"`
	CustomerId    int64       `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerPhone string      `protobuf:"bytes,6,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
	BillDesc      string      `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
	CustomerName  string      `protobuf:"bytes,9,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
	Item          []*ListItem `protobuf:"bytes,10,rep,name=Item,json=item,proto3" json:"Item,omitempty"`
}

func (x *SearchBillRespone) Reset() {
	*x = SearchBillRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBillRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBillRespone) ProtoMessage() {}

func (x *SearchBillRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBillRespone.ProtoReflect.Descriptor instead.
func (*SearchBillRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *SearchBillRespone) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *SearchBillRespone) GetBillStatus() int64 {
	if x != nil {
		return x.BillStatus
	}
	return 0
}

func (x *SearchBillRespone) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SearchBillRespone) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *SearchBillRespone) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

func (x *SearchBillRespone) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *SearchBillRespone) GetItem() []*ListItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   int64  `protobuf:"varint,1,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount   int64  `protobuf:"varint,2,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	ItemName string `protobuf:"bytes,3,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
}

func (x *ListItem) Reset() {
	*x = ListItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItem) ProtoMessage() {}

func (x *ListItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItem.ProtoReflect.Descriptor instead.
func (*ListItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *ListItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ListItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ListItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserToken string `protobuf:"bytes,8,opt,name=UserToken,json=userToken,proto3" json:"UserToken,omitempty"`
	//int64 ItemId = 3;
	//int64 Amount = 4;
	Item       []*CreateBillItem `protobuf:"bytes,2,rep,name=Item,json=item,proto3" json:"Item,omitempty"`
	CustomerId int64             `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	BillDesc   string            `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBillRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *CreateBillRequest) GetItem() []*CreateBillItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CreateBillRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateBillRequest) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

type CreateBillItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int64 `protobuf:"varint,1,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount int64 `protobuf:"varint,2,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
}

func (x *CreateBillItem) Reset() {
	*x = CreateBillItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillItem) ProtoMessage() {}

func (x *CreateBillItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillItem.ProtoReflect.Descriptor instead.
func (*CreateBillItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBillItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateBillItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateBillRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSaved int64 `protobuf:"varint,1,opt,name=IsSaved,json=isSaved,proto3" json:"IsSaved,omitempty"`
}

func (x *CreateBillRespone) Reset() {
	*x = CreateBillRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRespone) ProtoMessage() {}

func (x *CreateBillRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRespone.ProtoReflect.Descriptor instead.
func (*CreateBillRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBillRespone) GetIsSaved() int64 {
	if x != nil {
		return x.IsSaved
	}
	return 0
}

type ListItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListItemRequest) Reset() {
	*x = ListItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemRequest) ProtoMessage() {}

func (x *ListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemRequest.ProtoReflect.Descriptor instead.
func (*ListItemRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{7}
}

type ListItemRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*Item `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *ListItemRespone) Reset() {
	*x = ListItemRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemRespone) ProtoMessage() {}

func (x *ListItemRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemRespone.ProtoReflect.Descriptor instead.
func (*ListItemRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{8}
}

func (x *ListItemRespone) GetItem() []*Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName string `protobuf:"bytes,1,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	ItemId   int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{9}
}

func (x *Item) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Item) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type CustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerPhone string `protobuf:"bytes,1,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
}

func (x *CustomerRequest) Reset() {
	*x = CustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRequest) ProtoMessage() {}

func (x *CustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRequest.ProtoReflect.Descriptor instead.
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{10}
}

func (x *CustomerRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

type CustomerRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId    int64  `protobuf:"varint,1,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerName  string `protobuf:"bytes,2,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
	CustomerPhone string `protobuf:"bytes,3,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
}

func (x *CustomerRespone) Reset() {
	*x = CustomerRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRespone) ProtoMessage() {}

func (x *CustomerRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRespone.ProtoReflect.Descriptor instead.
func (*CustomerRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{11}
}

func (x *CustomerRespone) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CustomerRespone) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CustomerRespone) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserToken     string `protobuf:"bytes,10,opt,name=UserToken,json=userToken,proto3" json:"UserToken,omitempty"`
	BillId        int64  `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
	BillStatus    int64  `protobuf:"varint,2,opt,name=BillStatus,json=billStatus,proto3" json:"BillStatus,omitempty"`
	ItemId        int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount        int64  `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	CustomerId    int64  `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerPhone string `protobuf:"bytes,6,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
	BillDesc      string `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
	ItemName      string `protobuf:"bytes,8,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	CustomerName  string `protobuf:"bytes,9,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{12}
}

func (x *SearchRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *SearchRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *SearchRequest) GetBillStatus() int64 {
	if x != nil {
		return x.BillStatus
	}
	return 0
}

func (x *SearchRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SearchRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SearchRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SearchRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *SearchRequest) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

func (x *SearchRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SearchRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type SearchRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchRespones []*SearchBillRespone `protobuf:"bytes,1,rep,name=SearchRespones,json=searchRespones,proto3" json:"SearchRespones,omitempty"`
}

func (x *SearchRespone) Reset() {
	*x = SearchRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRespone) ProtoMessage() {}

func (x *SearchRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRespone.ProtoReflect.Descriptor instead.
func (*SearchRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRespone) GetSearchRespones() []*SearchBillRespone {
	if x != nil {
		return x.SearchRespones
	}
	return nil
}

type UserTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserToken string `protobuf:"bytes,1,opt,name=UserToken,json=userToken,proto3" json:"UserToken,omitempty"`
}

func (x *UserTokenRequest) Reset() {
	*x = UserTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokenRequest) ProtoMessage() {}

func (x *UserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokenRequest.ProtoReflect.Descriptor instead.
func (*UserTokenRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{14}
}

func (x *UserTokenRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

type UserTokenRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExisted  int64 `protobuf:"varint,1,opt,name=IsExisted,json=isExisted,proto3" json:"IsExisted,omitempty"`
	Authorized int64 `protobuf:"varint,2,opt,name=Authorized,json=authorized,proto3" json:"Authorized,omitempty"`
}

func (x *UserTokenRespone) Reset() {
	*x = UserTokenRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserTokenRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokenRespone) ProtoMessage() {}

func (x *UserTokenRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokenRespone.ProtoReflect.Descriptor instead.
func (*UserTokenRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{15}
}

func (x *UserTokenRespone) GetIsExisted() int64 {
	if x != nil {
		return x.IsExisted
	}
	return 0
}

func (x *UserTokenRespone) GetAuthorized() int64 {
	if x != nil {
		return x.Authorized
	}
	return 0
}

type BillDetailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId int64 `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
}

func (x *BillDetailRequest) Reset() {
	*x = BillDetailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillDetailRequest) ProtoMessage() {}

func (x *BillDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillDetailRequest.ProtoReflect.Descriptor instead.
func (*BillDetailRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{16}
}

func (x *BillDetailRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

type BillDetailRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListItem []*BillDetailItem `protobuf:"bytes,1,rep,name=ListItem,json=listItem,proto3" json:"ListItem,omitempty"`
	Total    int64             `protobuf:"varint,4,opt,name=Total,json=total,proto3" json:"Total,omitempty"`
}

func (x *BillDetailRespone) Reset() {
	*x = BillDetailRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillDetailRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillDetailRespone) ProtoMessage() {}

func (x *BillDetailRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillDetailRespone.ProtoReflect.Descriptor instead.
func (*BillDetailRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{17}
}

func (x *BillDetailRespone) GetListItem() []*BillDetailItem {
	if x != nil {
		return x.ListItem
	}
	return nil
}

func (x *BillDetailRespone) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BillDetailItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName string `protobuf:"bytes,1,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	Amount   int64  `protobuf:"varint,2,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price    int64  `protobuf:"varint,3,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
}

func (x *BillDetailItem) Reset() {
	*x = BillDetailItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillDetailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillDetailItem) ProtoMessage() {}

func (x *BillDetailItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillDetailItem.ProtoReflect.Descriptor instead.
func (*BillDetailItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{18}
}

func (x *BillDetailItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *BillDetailItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillDetailItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_protobuf_proto protoreflect.FileDescriptor

var file_protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x0d,
	0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x66, 0x0a, 0x0d, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x73, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x5f, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x22, 0xfd, 0x01,
	0x0a, 0x11, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42,
	0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x12, 0x22, 0x0a,
	0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x2a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x56, 0x0a,
	0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65,
	0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x30, 0x0a, 0x04, 0x49, 0x74, 0x65,
	0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x42,
	0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x22, 0x40, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x69, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x26,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x3a, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x7b, 0x0a, 0x0f, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0xb7, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65,
	0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x58, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x52, 0x0e, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x10,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x50,
	0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64,
	0x22, 0x2b, 0x0a, 0x11, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x63, 0x0a,
	0x11, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x22, 0x5a, 0x0a, 0x0e, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x8f,
	0x08, 0x0a, 0x19, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x4d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x77, 0x61, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0a,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65,
	0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x65, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f, 0x76,
	0x31, 0x2f, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2f, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x3a, 0x01, 0x2a, 0x12, 0x7e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69,
	0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61,
	0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x65, 0x22, 0x2e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x28, 0x22, 0x23, 0x2f, 0x76,
	0x31, 0x2f, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2f, 0x7b, 0x55, 0x73, 0x65, 0x72,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x7d, 0x2f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c,
	0x6c, 0x3a, 0x01, 0x2a, 0x12, 0x67, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x1d,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x2f, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x7a, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x2d, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x27, 0x12, 0x25, 0x2f, 0x76, 0x31, 0x2f, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2f, 0x7b, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x7d, 0x12, 0xb0, 0x02, 0x0a, 0x06, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0xeb,
	0x01, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0xe4, 0x01, 0x12, 0xe1, 0x01, 0x2f, 0x76, 0x31, 0x2f, 0x4d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x7d, 0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x49,
	0x64, 0x2f, 0x7b, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x7d, 0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2f, 0x7b, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x7d, 0x2f, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x7b, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x7d, 0x2f, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x2f, 0x7b, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x7d, 0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x2f, 0x7b, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x7d, 0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x2f, 0x7b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x7d, 0x2f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x2f, 0x7b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x7d, 0x2f, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x2f, 0x7b, 0x49,
	0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x7d, 0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73,
	0x63, 0x2f, 0x7b, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x7d, 0x12, 0x7c, 0x0a, 0x0e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x2a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x24, 0x12, 0x22, 0x2f, 0x76, 0x31, 0x2f, 0x4d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x2f, 0x7b,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x7d, 0x12, 0x74, 0x0a, 0x0a, 0x42, 0x69,
	0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x24, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1e, 0x12, 0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x4d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e, 0x74,
	0x2f, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x2f, 0x7b, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x7d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_rawDescOnce sync.Once
	file_protobuf_proto_rawDescData = file_protobuf_proto_rawDesc
)

func file_protobuf_proto_rawDescGZIP() []byte {
	file_protobuf_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_rawDescData)
	})
	return file_protobuf_proto_rawDescData
}

var file_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protobuf_proto_goTypes = []interface{}{
	(*AuthorRequest)(nil),     // 0: api.merchant.AuthorRequest
	(*AuthorRespone)(nil),     // 1: api.merchant.AuthorRespone
	(*SearchBillRespone)(nil), // 2: api.merchant.SearchBillRespone
	(*ListItem)(nil),          // 3: api.merchant.ListItem
	(*CreateBillRequest)(nil), // 4: api.merchant.CreateBillRequest
	(*CreateBillItem)(nil),    // 5: api.merchant.CreateBillItem
	(*CreateBillRespone)(nil), // 6: api.merchant.CreateBillRespone
	(*ListItemRequest)(nil),   // 7: api.merchant.ListItemRequest
	(*ListItemRespone)(nil),   // 8: api.merchant.ListItemRespone
	(*Item)(nil),              // 9: api.merchant.Item
	(*CustomerRequest)(nil),   // 10: api.merchant.CustomerRequest
	(*CustomerRespone)(nil),   // 11: api.merchant.CustomerRespone
	(*SearchRequest)(nil),     // 12: api.merchant.SearchRequest
	(*SearchRespone)(nil),     // 13: api.merchant.SearchRespone
	(*UserTokenRequest)(nil),  // 14: api.merchant.UserTokenRequest
	(*UserTokenRespone)(nil),  // 15: api.merchant.UserTokenRespone
	(*BillDetailRequest)(nil), // 16: api.merchant.BillDetailRequest
	(*BillDetailRespone)(nil), // 17: api.merchant.BillDetailRespone
	(*BillDetailItem)(nil),    // 18: api.merchant.BillDetailItem
}
var file_protobuf_proto_depIdxs = []int32{
	3,  // 0: api.merchant.SearchBillRespone.Item:type_name -> api.merchant.ListItem
	5,  // 1: api.merchant.CreateBillRequest.Item:type_name -> api.merchant.CreateBillItem
	9,  // 2: api.merchant.ListItemRespone.item:type_name -> api.merchant.Item
	2,  // 3: api.merchant.SearchRespone.SearchRespones:type_name -> api.merchant.SearchBillRespone
	18, // 4: api.merchant.BillDetailRespone.ListItem:type_name -> api.merchant.BillDetailItem
	0,  // 5: api.merchant.MerchantMiddlewareService.UserAuthor:input_type -> api.merchant.AuthorRequest
	4,  // 6: api.merchant.MerchantMiddlewareService.CreateBill:input_type -> api.merchant.CreateBillRequest
	7,  // 7: api.merchant.MerchantMiddlewareService.ListItem:input_type -> api.merchant.ListItemRequest
	10, // 8: api.merchant.MerchantMiddlewareService.GetCustomer:input_type -> api.merchant.CustomerRequest
	12, // 9: api.merchant.MerchantMiddlewareService.Search:input_type -> api.merchant.SearchRequest
	14, // 10: api.merchant.MerchantMiddlewareService.CheckUserToken:input_type -> api.merchant.UserTokenRequest
	16, // 11: api.merchant.MerchantMiddlewareService.BillDetail:input_type -> api.merchant.BillDetailRequest
	1,  // 12: api.merchant.MerchantMiddlewareService.UserAuthor:output_type -> api.merchant.AuthorRespone
	6,  // 13: api.merchant.MerchantMiddlewareService.CreateBill:output_type -> api.merchant.CreateBillRespone
	8,  // 14: api.merchant.MerchantMiddlewareService.ListItem:output_type -> api.merchant.ListItemRespone
	11, // 15: api.merchant.MerchantMiddlewareService.GetCustomer:output_type -> api.merchant.CustomerRespone
	13, // 16: api.merchant.MerchantMiddlewareService.Search:output_type -> api.merchant.SearchRespone
	15, // 17: api.merchant.MerchantMiddlewareService.CheckUserToken:output_type -> api.merchant.UserTokenRespone
	17, // 18: api.merchant.MerchantMiddlewareService.BillDetail:output_type -> api.merchant.BillDetailRespone
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protobuf_proto_init() }
func file_protobuf_proto_init() {
	if File_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBillRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItemRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserTokenRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillDetailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillDetailRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillDetailItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_depIdxs,
		MessageInfos:      file_protobuf_proto_msgTypes,
	}.Build()
	File_protobuf_proto = out.File
	file_protobuf_proto_rawDesc = nil
	file_protobuf_proto_goTypes = nil
	file_protobuf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MerchantMiddlewareServiceClient is the client API for MerchantMiddlewareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantMiddlewareServiceClient interface {
	UserAuthor(ctx context.Context, in *AuthorRequest, opts ...grpc.CallOption) (*AuthorRespone, error)
	CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillRespone, error)
	ListItem(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (*ListItemRespone, error)
	GetCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRespone, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchRespone, error)
	CheckUserToken(ctx context.Context, in *UserTokenRequest, opts ...grpc.CallOption) (*UserTokenRespone, error)
	BillDetail(ctx context.Context, in *BillDetailRequest, opts ...grpc.CallOption) (*BillDetailRespone, error)
}

type merchantMiddlewareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMerchantMiddlewareServiceClient(cc grpc.ClientConnInterface) MerchantMiddlewareServiceClient {
	return &merchantMiddlewareServiceClient{cc}
}

func (c *merchantMiddlewareServiceClient) UserAuthor(ctx context.Context, in *AuthorRequest, opts ...grpc.CallOption) (*AuthorRespone, error) {
	out := new(AuthorRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/UserAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillRespone, error) {
	out := new(CreateBillRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/CreateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) ListItem(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (*ListItemRespone, error) {
	out := new(ListItemRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/ListItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) GetCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRespone, error) {
	out := new(CustomerRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchRespone, error) {
	out := new(SearchRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) CheckUserToken(ctx context.Context, in *UserTokenRequest, opts ...grpc.CallOption) (*UserTokenRespone, error) {
	out := new(UserTokenRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/CheckUserToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantMiddlewareServiceClient) BillDetail(ctx context.Context, in *BillDetailRequest, opts ...grpc.CallOption) (*BillDetailRespone, error) {
	out := new(BillDetailRespone)
	err := c.cc.Invoke(ctx, "/api.merchant.MerchantMiddlewareService/BillDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantMiddlewareServiceServer is the server API for MerchantMiddlewareService service.
type MerchantMiddlewareServiceServer interface {
	UserAuthor(context.Context, *AuthorRequest) (*AuthorRespone, error)
	CreateBill(context.Context, *CreateBillRequest) (*CreateBillRespone, error)
	ListItem(context.Context, *ListItemRequest) (*ListItemRespone, error)
	GetCustomer(context.Context, *CustomerRequest) (*CustomerRespone, error)
	Search(context.Context, *SearchRequest) (*SearchRespone, error)
	CheckUserToken(context.Context, *UserTokenRequest) (*UserTokenRespone, error)
	BillDetail(context.Context, *BillDetailRequest) (*BillDetailRespone, error)
}

// UnimplementedMerchantMiddlewareServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMerchantMiddlewareServiceServer struct {
}

func (*UnimplementedMerchantMiddlewareServiceServer) UserAuthor(context.Context, *AuthorRequest) (*AuthorRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserAuthor not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) CreateBill(context.Context, *CreateBillRequest) (*CreateBillRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) ListItem(context.Context, *ListItemRequest) (*ListItemRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItem not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) GetCustomer(context.Context, *CustomerRequest) (*CustomerRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) Search(context.Context, *SearchRequest) (*SearchRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) CheckUserToken(context.Context, *UserTokenRequest) (*UserTokenRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUserToken not implemented")
}
func (*UnimplementedMerchantMiddlewareServiceServer) BillDetail(context.Context, *BillDetailRequest) (*BillDetailRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BillDetail not implemented")
}

func RegisterMerchantMiddlewareServiceServer(s *grpc.Server, srv MerchantMiddlewareServiceServer) {
	s.RegisterService(&_MerchantMiddlewareService_serviceDesc, srv)
}

func _MerchantMiddlewareService_UserAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).UserAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/UserAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).UserAuthor(ctx, req.(*AuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/CreateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).CreateBill(ctx, req.(*CreateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_ListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).ListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/ListItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).ListItem(ctx, req.(*ListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).GetCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_CheckUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).CheckUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/CheckUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).CheckUserToken(ctx, req.(*UserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantMiddlewareService_BillDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BillDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantMiddlewareServiceServer).BillDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.merchant.MerchantMiddlewareService/BillDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantMiddlewareServiceServer).BillDetail(ctx, req.(*BillDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantMiddlewareService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.merchant.MerchantMiddlewareService",
	HandlerType: (*MerchantMiddlewareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserAuthor",
			Handler:    _MerchantMiddlewareService_UserAuthor_Handler,
		},
		{
			MethodName: "CreateBill",
			Handler:    _MerchantMiddlewareService_CreateBill_Handler,
		},
		{
			MethodName: "ListItem",
			Handler:    _MerchantMiddlewareService_ListItem_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _MerchantMiddlewareService_GetCustomer_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MerchantMiddlewareService_Search_Handler,
		},
		{
			MethodName: "CheckUserToken",
			Handler:    _MerchantMiddlewareService_CheckUserToken_Handler,
		},
		{
			MethodName: "BillDetail",
			Handler:    _MerchantMiddlewareService_BillDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf.proto",
}
