// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: protobuf.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SearchBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserToken     string `protobuf:"bytes,10,opt,name=UserToken,json=userToken,proto3" json:"UserToken,omitempty"`
	BillId        int64  `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
	BillStatus    int64  `protobuf:"varint,2,opt,name=BillStatus,json=billStatus,proto3" json:"BillStatus,omitempty"`
	ItemId        int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount        int64  `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	CustomerId    int64  `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerPhone string `protobuf:"bytes,6,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
	BillDesc      string `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
	ItemName      string `protobuf:"bytes,8,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	CustomerName  string `protobuf:"bytes,9,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
}

func (x *SearchBillRequest) Reset() {
	*x = SearchBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBillRequest) ProtoMessage() {}

func (x *SearchBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBillRequest.ProtoReflect.Descriptor instead.
func (*SearchBillRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *SearchBillRequest) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *SearchBillRequest) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *SearchBillRequest) GetBillStatus() int64 {
	if x != nil {
		return x.BillStatus
	}
	return 0
}

func (x *SearchBillRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SearchBillRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SearchBillRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SearchBillRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *SearchBillRequest) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

func (x *SearchBillRequest) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *SearchBillRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

type SearchBillRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BillId        int64  `protobuf:"varint,1,opt,name=BillId,json=billId,proto3" json:"BillId,omitempty"`
	BillStatus    int64  `protobuf:"varint,2,opt,name=BillStatus,json=billStatus,proto3" json:"BillStatus,omitempty"`
	CustomerId    int64  `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerPhone string `protobuf:"bytes,6,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
	BillDesc      string `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
	CustomerName  string `protobuf:"bytes,9,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
	ItemId        int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount        int64  `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	ItemName      string `protobuf:"bytes,8,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
}

func (x *SearchBillRespone) Reset() {
	*x = SearchBillRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchBillRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchBillRespone) ProtoMessage() {}

func (x *SearchBillRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchBillRespone.ProtoReflect.Descriptor instead.
func (*SearchBillRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *SearchBillRespone) GetBillId() int64 {
	if x != nil {
		return x.BillId
	}
	return 0
}

func (x *SearchBillRespone) GetBillStatus() int64 {
	if x != nil {
		return x.BillStatus
	}
	return 0
}

func (x *SearchBillRespone) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *SearchBillRespone) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *SearchBillRespone) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

func (x *SearchBillRespone) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *SearchBillRespone) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SearchBillRespone) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SearchBillRespone) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type CreateBillRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item       []*CreateBillItem `protobuf:"bytes,3,rep,name=Item,json=item,proto3" json:"Item,omitempty"`
	CustomerId int64             `protobuf:"varint,5,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	BillDesc   string            `protobuf:"bytes,7,opt,name=BillDesc,json=billDesc,proto3" json:"BillDesc,omitempty"`
}

func (x *CreateBillRequest) Reset() {
	*x = CreateBillRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRequest) ProtoMessage() {}

func (x *CreateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRequest.ProtoReflect.Descriptor instead.
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBillRequest) GetItem() []*CreateBillItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *CreateBillRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateBillRequest) GetBillDesc() string {
	if x != nil {
		return x.BillDesc
	}
	return ""
}

type CreateBillItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int64 `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
	Amount int64 `protobuf:"varint,4,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
}

func (x *CreateBillItem) Reset() {
	*x = CreateBillItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillItem) ProtoMessage() {}

func (x *CreateBillItem) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillItem.ProtoReflect.Descriptor instead.
func (*CreateBillItem) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBillItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *CreateBillItem) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateBillRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSaved int64 `protobuf:"varint,1,opt,name=IsSaved,json=isSaved,proto3" json:"IsSaved,omitempty"`
}

func (x *CreateBillRespone) Reset() {
	*x = CreateBillRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBillRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillRespone) ProtoMessage() {}

func (x *CreateBillRespone) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillRespone.ProtoReflect.Descriptor instead.
func (*CreateBillRespone) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{4}
}

func (x *CreateBillRespone) GetIsSaved() int64 {
	if x != nil {
		return x.IsSaved
	}
	return 0
}

var File_protobuf_proto protoreflect.FileDescriptor

var file_protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0xbb, 0x02, 0x0a, 0x11, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x69, 0x6c, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x9d, 0x02, 0x0a, 0x11, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x62, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x42, 0x69, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x69, 0x6c, 0x6c,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x62, 0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x42,
	0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62,
	0x69, 0x6c, 0x6c, 0x44, 0x65, 0x73, 0x63, 0x22, 0x40, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x42, 0x69, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x69, 0x73, 0x53, 0x61, 0x76, 0x65, 0x64, 0x32, 0xa2, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x4a, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x42, 0x69, 0x6c, 0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x6c,
	0x6c, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x42, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_rawDescOnce sync.Once
	file_protobuf_proto_rawDescData = file_protobuf_proto_rawDesc
)

func file_protobuf_proto_rawDescGZIP() []byte {
	file_protobuf_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_rawDescData)
	})
	return file_protobuf_proto_rawDescData
}

var file_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_proto_goTypes = []interface{}{
	(*SearchBillRequest)(nil), // 0: protobuf.SearchBillRequest
	(*SearchBillRespone)(nil), // 1: protobuf.SearchBillRespone
	(*CreateBillRequest)(nil), // 2: protobuf.CreateBillRequest
	(*CreateBillItem)(nil),    // 3: protobuf.CreateBillItem
	(*CreateBillRespone)(nil), // 4: protobuf.CreateBillRespone
}
var file_protobuf_proto_depIdxs = []int32{
	3, // 0: protobuf.CreateBillRequest.Item:type_name -> protobuf.CreateBillItem
	0, // 1: protobuf.ManageBill.SearchBill:input_type -> protobuf.SearchBillRequest
	2, // 2: protobuf.ManageBill.CreateBill:input_type -> protobuf.CreateBillRequest
	1, // 3: protobuf.ManageBill.SearchBill:output_type -> protobuf.SearchBillRespone
	4, // 4: protobuf.ManageBill.CreateBill:output_type -> protobuf.CreateBillRespone
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_proto_init() }
func file_protobuf_proto_init() {
	if File_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchBillRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBillRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_depIdxs,
		MessageInfos:      file_protobuf_proto_msgTypes,
	}.Build()
	File_protobuf_proto = out.File
	file_protobuf_proto_rawDesc = nil
	file_protobuf_proto_goTypes = nil
	file_protobuf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ManageBillClient is the client API for ManageBill service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManageBillClient interface {
	SearchBill(ctx context.Context, in *SearchBillRequest, opts ...grpc.CallOption) (ManageBill_SearchBillClient, error)
	CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillRespone, error)
}

type manageBillClient struct {
	cc grpc.ClientConnInterface
}

func NewManageBillClient(cc grpc.ClientConnInterface) ManageBillClient {
	return &manageBillClient{cc}
}

func (c *manageBillClient) SearchBill(ctx context.Context, in *SearchBillRequest, opts ...grpc.CallOption) (ManageBill_SearchBillClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ManageBill_serviceDesc.Streams[0], "/protobuf.ManageBill/SearchBill", opts...)
	if err != nil {
		return nil, err
	}
	x := &manageBillSearchBillClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ManageBill_SearchBillClient interface {
	Recv() (*SearchBillRespone, error)
	grpc.ClientStream
}

type manageBillSearchBillClient struct {
	grpc.ClientStream
}

func (x *manageBillSearchBillClient) Recv() (*SearchBillRespone, error) {
	m := new(SearchBillRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *manageBillClient) CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillRespone, error) {
	out := new(CreateBillRespone)
	err := c.cc.Invoke(ctx, "/protobuf.ManageBill/CreateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManageBillServer is the server API for ManageBill service.
type ManageBillServer interface {
	SearchBill(*SearchBillRequest, ManageBill_SearchBillServer) error
	CreateBill(context.Context, *CreateBillRequest) (*CreateBillRespone, error)
}

// UnimplementedManageBillServer can be embedded to have forward compatible implementations.
type UnimplementedManageBillServer struct {
}

func (*UnimplementedManageBillServer) SearchBill(*SearchBillRequest, ManageBill_SearchBillServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchBill not implemented")
}
func (*UnimplementedManageBillServer) CreateBill(context.Context, *CreateBillRequest) (*CreateBillRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}

func RegisterManageBillServer(s *grpc.Server, srv ManageBillServer) {
	s.RegisterService(&_ManageBill_serviceDesc, srv)
}

func _ManageBill_SearchBill_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchBillRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManageBillServer).SearchBill(m, &manageBillSearchBillServer{stream})
}

type ManageBill_SearchBillServer interface {
	Send(*SearchBillRespone) error
	grpc.ServerStream
}

type manageBillSearchBillServer struct {
	grpc.ServerStream
}

func (x *manageBillSearchBillServer) Send(m *SearchBillRespone) error {
	return x.ServerStream.SendMsg(m)
}

func _ManageBill_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageBillServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ManageBill/CreateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageBillServer).CreateBill(ctx, req.(*CreateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManageBill_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ManageBill",
	HandlerType: (*ManageBillServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBill",
			Handler:    _ManageBill_CreateBill_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchBill",
			Handler:       _ManageBill_SearchBill_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf.proto",
}
