// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: Proto/ManageBill

package ManageBill

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_Proto_ManageBill protoreflect.FileDescriptor

var file_Proto_ManageBill_rawDesc = []byte{
	0x0a, 0x10, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x42, 0x69,
	0x6c, 0x6c,
}

var file_Proto_ManageBill_goTypes = []interface{}{}
var file_Proto_ManageBill_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_ManageBill_init() }
func file_Proto_ManageBill_init() {
	if File_Proto_ManageBill != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_ManageBill_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Proto_ManageBill_goTypes,
		DependencyIndexes: file_Proto_ManageBill_depIdxs,
	}.Build()
	File_Proto_ManageBill = out.File
	file_Proto_ManageBill_rawDesc = nil
	file_Proto_ManageBill_goTypes = nil
	file_Proto_ManageBill_depIdxs = nil
}
