// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: ManageSupport/protobuf.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ListItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListItemRequest) Reset() {
	*x = ListItemRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ManageSupport_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemRequest) ProtoMessage() {}

func (x *ListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ManageSupport_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemRequest.ProtoReflect.Descriptor instead.
func (*ListItemRequest) Descriptor() ([]byte, []int) {
	return file_ManageSupport_protobuf_proto_rawDescGZIP(), []int{0}
}

type ListItemRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemName string `protobuf:"bytes,1,opt,name=ItemName,json=itemName,proto3" json:"ItemName,omitempty"`
	ItemId   int64  `protobuf:"varint,3,opt,name=ItemId,json=itemId,proto3" json:"ItemId,omitempty"`
}

func (x *ListItemRespone) Reset() {
	*x = ListItemRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ManageSupport_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListItemRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemRespone) ProtoMessage() {}

func (x *ListItemRespone) ProtoReflect() protoreflect.Message {
	mi := &file_ManageSupport_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemRespone.ProtoReflect.Descriptor instead.
func (*ListItemRespone) Descriptor() ([]byte, []int) {
	return file_ManageSupport_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemRespone) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ListItemRespone) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type CustomerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerPhone string `protobuf:"bytes,1,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
}

func (x *CustomerRequest) Reset() {
	*x = CustomerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ManageSupport_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRequest) ProtoMessage() {}

func (x *CustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ManageSupport_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRequest.ProtoReflect.Descriptor instead.
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return file_ManageSupport_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerRequest) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

type CustomerRespone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomerId    int64  `protobuf:"varint,1,opt,name=CustomerId,json=customerId,proto3" json:"CustomerId,omitempty"`
	CustomerName  string `protobuf:"bytes,2,opt,name=CustomerName,json=customerName,proto3" json:"CustomerName,omitempty"`
	CustomerPhone string `protobuf:"bytes,3,opt,name=CustomerPhone,json=customerPhone,proto3" json:"CustomerPhone,omitempty"`
}

func (x *CustomerRespone) Reset() {
	*x = CustomerRespone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ManageSupport_protobuf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRespone) ProtoMessage() {}

func (x *CustomerRespone) ProtoReflect() protoreflect.Message {
	mi := &file_ManageSupport_protobuf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRespone.ProtoReflect.Descriptor instead.
func (*CustomerRespone) Descriptor() ([]byte, []int) {
	return file_ManageSupport_protobuf_proto_rawDescGZIP(), []int{3}
}

func (x *CustomerRespone) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CustomerRespone) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *CustomerRespone) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

var File_ManageSupport_protobuf_proto protoreflect.FileDescriptor

var file_ManageSupport_protobuf_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x22, 0x7b, 0x0a, 0x0f, 0x43,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x32, 0x9f, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x47, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ManageSupport_protobuf_proto_rawDescOnce sync.Once
	file_ManageSupport_protobuf_proto_rawDescData = file_ManageSupport_protobuf_proto_rawDesc
)

func file_ManageSupport_protobuf_proto_rawDescGZIP() []byte {
	file_ManageSupport_protobuf_proto_rawDescOnce.Do(func() {
		file_ManageSupport_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_ManageSupport_protobuf_proto_rawDescData)
	})
	return file_ManageSupport_protobuf_proto_rawDescData
}

var file_ManageSupport_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ManageSupport_protobuf_proto_goTypes = []interface{}{
	(*ListItemRequest)(nil), // 0: protobuf.ListItemRequest
	(*ListItemRespone)(nil), // 1: protobuf.ListItemRespone
	(*CustomerRequest)(nil), // 2: protobuf.CustomerRequest
	(*CustomerRespone)(nil), // 3: protobuf.CustomerRespone
}
var file_ManageSupport_protobuf_proto_depIdxs = []int32{
	0, // 0: protobuf.ManageSupport.GetListItem:input_type -> protobuf.ListItemRequest
	2, // 1: protobuf.ManageSupport.GetCustomer:input_type -> protobuf.CustomerRequest
	1, // 2: protobuf.ManageSupport.GetListItem:output_type -> protobuf.ListItemRespone
	3, // 3: protobuf.ManageSupport.GetCustomer:output_type -> protobuf.CustomerRespone
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ManageSupport_protobuf_proto_init() }
func file_ManageSupport_protobuf_proto_init() {
	if File_ManageSupport_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ManageSupport_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItemRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ManageSupport_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListItemRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ManageSupport_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ManageSupport_protobuf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerRespone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ManageSupport_protobuf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ManageSupport_protobuf_proto_goTypes,
		DependencyIndexes: file_ManageSupport_protobuf_proto_depIdxs,
		MessageInfos:      file_ManageSupport_protobuf_proto_msgTypes,
	}.Build()
	File_ManageSupport_protobuf_proto = out.File
	file_ManageSupport_protobuf_proto_rawDesc = nil
	file_ManageSupport_protobuf_proto_goTypes = nil
	file_ManageSupport_protobuf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ManageSupportClient is the client API for ManageSupport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManageSupportClient interface {
	GetListItem(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (ManageSupport_GetListItemClient, error)
	GetCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRespone, error)
}

type manageSupportClient struct {
	cc grpc.ClientConnInterface
}

func NewManageSupportClient(cc grpc.ClientConnInterface) ManageSupportClient {
	return &manageSupportClient{cc}
}

func (c *manageSupportClient) GetListItem(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (ManageSupport_GetListItemClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ManageSupport_serviceDesc.Streams[0], "/protobuf.ManageSupport/GetListItem", opts...)
	if err != nil {
		return nil, err
	}
	x := &manageSupportGetListItemClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ManageSupport_GetListItemClient interface {
	Recv() (*ListItemRespone, error)
	grpc.ClientStream
}

type manageSupportGetListItemClient struct {
	grpc.ClientStream
}

func (x *manageSupportGetListItemClient) Recv() (*ListItemRespone, error) {
	m := new(ListItemRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *manageSupportClient) GetCustomer(ctx context.Context, in *CustomerRequest, opts ...grpc.CallOption) (*CustomerRespone, error) {
	out := new(CustomerRespone)
	err := c.cc.Invoke(ctx, "/protobuf.ManageSupport/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManageSupportServer is the server API for ManageSupport service.
type ManageSupportServer interface {
	GetListItem(*ListItemRequest, ManageSupport_GetListItemServer) error
	GetCustomer(context.Context, *CustomerRequest) (*CustomerRespone, error)
}

// UnimplementedManageSupportServer can be embedded to have forward compatible implementations.
type UnimplementedManageSupportServer struct {
}

func (*UnimplementedManageSupportServer) GetListItem(*ListItemRequest, ManageSupport_GetListItemServer) error {
	return status.Errorf(codes.Unimplemented, "method GetListItem not implemented")
}
func (*UnimplementedManageSupportServer) GetCustomer(context.Context, *CustomerRequest) (*CustomerRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}

func RegisterManageSupportServer(s *grpc.Server, srv ManageSupportServer) {
	s.RegisterService(&_ManageSupport_serviceDesc, srv)
}

func _ManageSupport_GetListItem_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListItemRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManageSupportServer).GetListItem(m, &manageSupportGetListItemServer{stream})
}

type ManageSupport_GetListItemServer interface {
	Send(*ListItemRespone) error
	grpc.ServerStream
}

type manageSupportGetListItemServer struct {
	grpc.ServerStream
}

func (x *manageSupportGetListItemServer) Send(m *ListItemRespone) error {
	return x.ServerStream.SendMsg(m)
}

func _ManageSupport_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageSupportServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.ManageSupport/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageSupportServer).GetCustomer(ctx, req.(*CustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ManageSupport_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.ManageSupport",
	HandlerType: (*ManageSupportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomer",
			Handler:    _ManageSupport_GetCustomer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetListItem",
			Handler:       _ManageSupport_GetListItem_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ManageSupport/protobuf.proto",
}
